### ISSUE TITLE
Sorting Algorithm in Python

### ISSUE THREAD

**Issue by tarunjain1st** [tarunjain1st/DSA_Notebook#1]
## Sorting Algorithm in Python

- [x] Insertion Sort

- [x] Selection Sort

- [x] Bubble Sort

- [x] Heap Sort

- [x] Quick Sort

- [x] Radix Sort

- [x] Merge Sort

- [ ] Topological Sort

- [x] Shell Sort

- [x] Tree Sort

**Comment by percygautam** [comment]
I'd like to do bubble and insertion sort

**Comment by tarunjain1st** [comment]
okay @percygautam

**Comment by IamShubhamGupto** [comment]
Id like to add merge sort. I can also provide quicksort if you add that to the todo list.

**Comment by tarunjain1st** [comment]
@IamShubhamGupto you can go merge sort, as Quick Sort is already assigned to someone else

**Comment by tdchua** [comment]
Hi! Please assign me Selection Sort and Heap Sort :D

**Comment by tarunjain1st** [comment]
okay @tdchua go ahead

**Comment by AlxGration** [comment]
let me write radix sort)

**Comment by tarunjain1st** [comment]
Sure @AlxGration go ahead

**Comment by tdchua** [comment]
Hi! It says that this repository is excluded in Hacktoberfest?
