### ISSUE TITLE
Searching Algorithms in Python

### ISSUE THREAD

**Issue by tarunjain1st** [tarunjain1st/DSA_Notebook#2]
## Searching Algorithms in Python

- [x] Linear Search

- [x] Binary Search

- [ ] Bilinear Search (Improvised version of Linear Search)

- [x] Breadth First Search

- [x] Depth First Search

- [ ] Exponential Search

- [ ] Interpolation Search

- [x] Z Algorithm

- [ ] Fibonacci Search

- [ ] Jump Search

- [ ] Ternary Search

- [ ] Sublist Search

**Comment by thegauravagrawal** [comment]
I would like to add some can you assign it to me?

**Comment by tarunjain1st** [comment]
Yes @thegauravagrawal  tell me which one do you want

**Comment by thegauravagrawal** [comment]
@tarunjain1st linear search and binary search

**Comment by tarunjain1st** [comment]
okay @thegauravagrawal go ahead i'll assign both

**Comment by percygautam** [comment]
I'll do BFS and DFS

**Comment by tarunjain1st** [comment]
@percygautam wait for the issue assigned to you, next time when you make a changes

**Comment by SayaniG371** [comment]
I would like to contribute to Z-Algorithm . Please Assign me that

**Comment by tarunjain1st** [comment]
sure @SayaniG371 go ahead

**Comment by tdchua** [comment]
I'd like to do jump search and fibonacci search :D
