### ISSUE TITLE
Caesar Cipher Algorithm

### ISSUE THREAD

**Issue by SayaniG371** [tarunjain1st/DSA_Notebook#21]
Caesar Cipher Algorithm is a basic algorithm of encoding a message with a key.

**Comment by SayaniG371** [comment]
@tarunjain1st I would like to add this. Please assign me

**Comment by tarunjain1st** [comment]
Sure @SayaniG371 go ahead

**Comment by SayaniG371** [comment]
Hello, would you please add the label of HacktoberFest in both my issues?
And can I make a new folder for Ciphering Algorithms?
