### ISSUE TITLE
Autokey Cipher

### ISSUE THREAD

**Issue by SayaniG371** [tarunjain1st/DSA_Notebook#22]
Autokey Cipher is a ciphering technique that incorporates the message for creating the key.

**Comment by SayaniG371** [comment]
@tarunjain1st I would like to add this too 😄

**Comment by tarunjain1st** [comment]
go ahead

**Comment by SayaniG371** [comment]
Hello sir, why is the issue closed? I thought I was assigned sir @tarunjain1st

**Comment by tarunjain1st** [comment]
you can make a PR as this issue is not for others and rest all issues are completely done.
don't worry you can upload your code and make a PR

**Comment by SayaniG371** [comment]
Ok sir thank you
