### ISSUE TITLE
String/Pattern Matching

### ISSUE THREAD

**Issue by IamShubhamGupto** [tarunjain1st/DSA_Notebook#23]
## There are many pattern matching algorithms which can be utilized in DSA. Some of which are:
- [ ] Naive String Matching
- [ ] Modified String Matching
- [ ] Rabin Karp Algorithm
- [ ] Knuth Morris Prath Algorithm
- [ ] String Matching using FSM
### Can be implemented in any language, preferably:
- [ ] C
- [ ] Java
- [ ] python

**Comment by IamShubhamGupto** [comment]
@tarunjain1st Id like to contribute these algorithms in C. Please add the respective labels for this issue

**Comment by tarunjain1st** [comment]
Sure
