### ISSUE TITLE
Intermediate Sorting Algorithms in Python

### ISSUE THREAD

**Issue by tarunjain1st** [tarunjain1st/DSA_Notebook#3]
## Intermediate Sorting Algorithms in Python

- [ ] Wiggle sort

- [x] Tree sort

- [x] Shell sort

- [x] Tim sort

- [x] Stooge sort

- [ ] Recursive Quick Sort

- [x] Recursive Insertion Sort

- [x] Recursive Bubble Sort

- [ ] Random Pivot Quick Sort

- [ ] Bead Sort

- [ ] Bitonic Sort

- [ ] Bogo Sort

- [x] Bucket Sort

- [ ] Cocktail Shaker Sort

- [ ] Comb Sort

- [ ] Pigeon Sort

- [ ] Pancake Sort

- [ ] Gnome Sort

- [ ] External Sort

- [ ] Double Sort

- [ ] Cycle Sort

**Comment by IamShubhamGupto** [comment]
id like to add recursive bubble sort.

**Comment by tarunjain1st** [comment]
Sure @IamShubhamGupto go ahead

**Comment by Vaibhav7860** [comment]
Sir I would love to add Recursive Selection Sort

**Comment by Vaibhav7860** [comment]
Sir I would like to add Recursive Insertion sort. Can I add?

**Comment by tarunjain1st** [comment]
Sure @Vaibhav7860 go ahead

**Comment by Vaibhav7860** [comment]
@tarunjain1st  Sir, I was trying to make my first pull request to this repository. So, for that I was directly uploading my Recursive Insertion Sort file but it was showing Uploads are disabled, File uploads require push access to this repository. Sir kindly guide me how to upload my code and make the pull request.
Thank You

**Comment by Vaibhav7860** [comment]
@tarunjain1st Sir now I have succesfully uploaded my code and made the pull request. Kindly review it.
