### ISSUE TITLE
Linked List

### ISSUE THREAD

**Issue by tarunjain1st** [tarunjain1st/DSA_Notebook#4]
## Implementation of the following in Python:

- [x] Singly Linked List

- [x] Doubly Linked List

- [x] Circular Linked List

- [ ] Implementing Deque using DoublyLinkedList

- [ ] Printing the elements of a linked list in reverse

**Comment by hemantsirsat** [comment]
interested

**Comment by tarunjain1st** [comment]
@hemantsirsat  name which one do you want to work on from the above options

**Comment by hemantsirsat** [comment]
@tarunjain1st Singly linked list along with printing elements in reverse.

**Comment by SravanthiKaki** [comment]
Can you assign this to me? I want to work on singly linked list

**Comment by SravanthiKaki** [comment]
Can you assign this to me? I want to work on circular linked list

**Comment by tarunjain1st** [comment]
Okay @hemantsirsat you can work on that I'll assign it to you

**Comment by tarunjain1st** [comment]
Okay @SravanthiKaki go ahead I'll assign it to you

**Comment by IamShubhamGupto** [comment]
Hey
For the linked list implementations, I noticed there are no C lang solutions. Can you assign me with implementing single and doublly linked list in C ?

**Comment by tarunjain1st** [comment]
Yes @IamShubhamGupto go ahead

**Comment by tdchua** [comment]
Hi! I would like to work on Doubly Linked List  :D Please assign me and thank you!

**Comment by tarunjain1st** [comment]
sure @tdchua  go ahead
